"""certificate issuances

Revision ID: 4e5efe56a864
Revises: d8ffbbdb4cc7
Create Date: 2026-09-30 00:10:02.895267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5efe56a864'
down_revision: Union[str, None] = 'd8ffbbdb4cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_issuances',
    sa.Column('issue_no', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('issued_by', sa.String(length=32), nullable=True),
    sa.Column('anchor_status', sa.String(length=16), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('issue_no'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_certificate_issuances_contract_id'), 'certificate_issuances', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_issuances_contract_id'), table_name='certificate_issuances')
    op.drop_table('certificate_issuances')
    # ### end Alembic commands ###
