"""initial schema

Revision ID: d8ffbbdb4cc7
Revises: 
Create Date: 2026-09-29 22:01:00.138911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ffbbdb4cc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_kv',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dev_faults',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mock_ledger',
    sa.Column('tx_id', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tx_id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_key', sa.String(length=128), nullable=False),
    sa.Column('display_name_masked', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_key')
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_no', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('final_version_no', sa.Integer(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_id', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('keep_encrypted_original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no'),
    sa.UniqueConstraint('verification_id')
    )
    op.create_index(op.f('ix_contracts_document_hash'), 'contracts', ['document_hash'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('contract_id', 'seq')
    )
    op.create_index(op.f('ix_audit_events_contract_id'), 'audit_events', ['contract_id'], unique=False)
    op.create_table('contract_parties',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('display_name_masked', sa.String(length=64), nullable=True),
    sa.Column('invite_token_hash', sa.String(length=64), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identity_status', sa.String(length=16), nullable=False),
    sa.Column('identity_provider', sa.String(length=32), nullable=True),
    sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_version_no', sa.Integer(), nullable=True),
    sa.Column('signature_status', sa.String(length=16), nullable=False),
    sa.Column('signature_provider', sa.String(length=32), nullable=True),
    sa.Column('signature_request_id', sa.String(length=64), nullable=True),
    sa.Column('signature_ref', sa.String(length=128), nullable=True),
    sa.Column('signed_version_no', sa.Integer(), nullable=True),
    sa.Column('signed_content_hash', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_parties_contract_id'), 'contract_parties', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_parties_invite_token_hash'), 'contract_parties', ['invite_token_hash'], unique=False)
    op.create_table('document_blobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.String(length=32), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_blobs_contract_id'), 'document_blobs', ['contract_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sealed', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('payload_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('payload_wrapped_dek', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.String(length=32), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'version_no')
    )
    op.create_index(op.f('ix_document_versions_contract_id'), 'document_versions', ['contract_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payments_contract_id'), 'payments', ['contract_id'], unique=False)
    op.create_table('anchor_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=False),
    sa.Column('tx_id', sa.String(length=128), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('anchored_value', sa.String(length=64), nullable=True),
    sa.Column('merkle_proof', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_anchor_jobs_contract_id'), 'anchor_jobs', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anchor_jobs_contract_id'), table_name='anchor_jobs')
    op.drop_table('anchor_jobs')
    op.drop_index(op.f('ix_payments_contract_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_document_versions_contract_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_blobs_contract_id'), table_name='document_blobs')
    op.drop_table('document_blobs')
    op.drop_index(op.f('ix_contract_parties_invite_token_hash'), table_name='contract_parties')
    op.drop_index(op.f('ix_contract_parties_contract_id'), table_name='contract_parties')
    op.drop_table('contract_parties')
    op.drop_index(op.f('ix_audit_events_contract_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_contracts_document_hash'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('users')
    op.drop_table('mock_ledger')
    op.drop_table('dev_faults')
    op.drop_table('app_kv')
    # ### end Alembic commands ###
